spring:
#  liquibase:
#    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5435/labDB
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: false

jwt:
  secret-word: megaSecretWordInTheWorld
  hours: 1
  prefix: "Bearer "
  access-token-key: Authorization